version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - db
    environment:
      - REACT_APP_API_URL=http://localhost:8080
    networks:
      - aircon-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: aircon_db
      MYSQL_USER: aircon_user
      MYSQL_PASSWORD: aircon_password
    networks:
      - aircon-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/aircon_db
      - SPRING_DATASOURCE_USERNAME=aircon_user
      - SPRING_DATASOURCE_PASSWORD=aircon_password
    networks:
      - aircon-network

networks:
  aircon-network:
    driver: bridge

volumes:
  mysql-data: 